import { unsplash } from "@/lib/unsplash";
import type { Project, ProjectCategory } from "@/types";

export const projectCategories: { value: ProjectCategory | "all"; label: string }[] = [
  { value: "all", label: "All Projects" },
  { value: "villas", label: "Villas" },
  { value: "resorts", label: "Resorts" },
  { value: "residential", label: "Residential" },
  { value: "commercial", label: "Commercial" },
  { value: "vertical-gardens", label: "Vertical Gardens" },
];

export const projects: Project[] = [
  {
    slug: "kaloor-villa-courtyard",
    title: "Kaloor Villa Courtyard",
    location: "Kochi, Kerala",
    category: "villas",
    categoryLabel: "Villas",
    year: "2025",
    image: {
      src: unsplash("1721989519334-40923a0ee1c0", 1200, 1500),
      alt: "Landscaped courtyard of a modern villa with a swimming pool",
      recommendedFilename: "higarden-project-kaloor-villa-courtyard.jpg",
    },
    aspectClass: "aspect-[4/5]",
  },
  {
    slug: "backwater-resort-gardens",
    title: "Backwater Resort Gardens",
    location: "Alleppey, Kerala",
    category: "resorts",
    categoryLabel: "Resorts",
    year: "2024",
    image: {
      src: unsplash("1766483683187-28ccf8662268", 1200, 900),
      alt: "Kerala backwater resort buildings framed by palm trees",
      recommendedFilename: "higarden-project-backwater-resort-gardens.jpg",
    },
    aspectClass: "aspect-[4/3]",
  },
  {
    slug: "cafe-living-wall",
    title: "Cafe Living Wall",
    location: "Thiruvananthapuram, Kerala",
    category: "vertical-gardens",
    categoryLabel: "Vertical Gardens",
    year: "2025",
    image: {
      src: unsplash("1490187763999-9f273a5b7516", 1200, 1600),
      alt: "Modular living wall of hanging planters being installed",
      recommendedFilename: "higarden-project-cafe-living-wall.jpg",
    },
    aspectClass: "aspect-[3/4]",
  },
  {
    slug: "kollam-residence-garden",
    title: "Kollam Residence Garden",
    location: "Kollam, Kerala",
    category: "residential",
    categoryLabel: "Residential",
    year: "2024",
    image: {
      src: unsplash("1741541149020-02dbb11ebd37", 1200, 900),
      alt: "Traditional Kerala home nestled among lush greenery",
      recommendedFilename: "higarden-project-kollam-residence-garden.jpg",
    },
    aspectClass: "aspect-[4/3]",
  },
  {
    slug: "tech-park-commercial-grounds",
    title: "Tech Park Commercial Grounds",
    location: "Kochi, Kerala",
    category: "commercial",
    categoryLabel: "Commercial",
    year: "2023",
    image: {
      src: unsplash("1777196963452-03ac60099b9b", 1200, 1500),
      alt: "Modern office buildings framed by green lawns and trees",
      recommendedFilename: "higarden-project-tech-park-commercial-grounds.jpg",
    },
    aspectClass: "aspect-[4/5]",
  },
  {
    slug: "hillside-villa-terraces",
    title: "Hillside Villa Terraces",
    location: "Munnar, Kerala",
    category: "villas",
    categoryLabel: "Villas",
    year: "2023",
    image: {
      src: unsplash("1766025065806-0ed92891692d", 1200, 900),
      alt: "Terraced green fields cascading down a hillside valley",
      recommendedFilename: "higarden-project-hillside-villa-terraces.jpg",
    },
    aspectClass: "aspect-[4/3]",
  },
  {
    slug: "boutique-resort-pathways",
    title: "Boutique Resort Pathways",
    location: "Wayanad, Kerala",
    category: "resorts",
    categoryLabel: "Resorts",
    year: "2025",
    image: {
      src: unsplash("1740924771376-7396a0c0c8ca", 1200, 1600),
      alt: "Palm-lined pathway through a tropical resort garden",
      recommendedFilename: "higarden-project-boutique-resort-pathways.jpg",
    },
    aspectClass: "aspect-[3/4]",
  },
  {
    slug: "fort-kochi-townhouse",
    title: "Fort Kochi Townhouse Garden",
    location: "Fort Kochi, Kerala",
    category: "residential",
    categoryLabel: "Residential",
    year: "2024",
    image: {
      src: unsplash("1565255822848-80db21938837", 1200, 900),
      alt: "Compact Kochi townhouse with potted plants at the entrance",
      recommendedFilename: "higarden-project-fort-kochi-townhouse.jpg",
    },
    aspectClass: "aspect-[4/3]",
  },
  {
    slug: "office-atrium-vertical-garden",
    title: "Office Atrium Vertical Garden",
    location: "Kochi, Kerala",
    category: "vertical-gardens",
    categoryLabel: "Vertical Gardens",
    year: "2022",
    image: {
      src: unsplash("1782177387992-e01c8b260a6e", 1200, 1500),
      alt: "Vertical garden wall installed inside an office atrium",
      recommendedFilename: "higarden-project-office-atrium-vertical-garden.jpg",
    },
    aspectClass: "aspect-[4/5]",
  },
];
